# Configure the framework that is going to be used
# framework:
#   {{ if eq .Project.Framework.Type "dotnet" }}
#   name: dotnet
#   commands:
#     - name: dotnet
#       version: "> 6.0, < 6.1"
#   {{ end }}
#   {{ if eq .Project.Framework.Type "dotnet" }}
#   name: java
#   commands:
#     - name: java
#       version: ">= 11"
#   {{ end }}
#   {{ if eq .Project.Framework.Type "node" }}
#   name: node
#   commands:
#     - name: node
#       version: ">= 18.3"
#   {{ end }}

# Pipeline files
pipeline:
  - type: azdo
    files:
      - name: build
        path: cicd/build/azdo/pipeline.yml
      - name: variable
        path: cicd/build/azdo/pipeline-vars.yml
    templates:
      - name: variable
        path: cicd/scaffold/azdo/pipeline-vars.yml

  - type: gha

setup:
  operations:
    - action: copy
